### ISSUE TITLE
implement architecture for stage

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#404]
- [x] add a tasks table (more like httpobs) with columns ID: inserted_at, updated_at, k8s job id, status (requested, running, completed, errored) #419
- [x] modify task create API view to save to tasks w/ status requested #420
- [x] modify task logs and read API views to read from the tasks table #420 
- [x] add a worker process (single container deployment in the web cluster); celery shouldn’t be necessary
   - [x] runs with `worker` subcommand
   - [x] reads requested jobs (TODO: de-dupe and rate limit them or handle that in k8s)
   - [x] kicks off jobs in the untrusted cluster
   - [x] reads the results from pubsub and saves them to the DB as `JSONResult` 
   - [x] parses and saves `JSONResults` to other tables and scores packages
- [x] remove the unused env vars #420
- [x] add pubsub topic name env var #420
- [x] modify scan envs script to buffer and write stdout to pubsub #415

**Comment by g-k** [comment]
Closing this. Still need to fix the render logs UI.
